[package]
edition = "2021"
name = "methods-guest"
version = "0.1.0"

[workspace]

[build-dependencies]
risc0-build = "0.10"

[dependencies]
risc0-zkvm-guest = "0.10"
risc0-zkvm-serde = "0.10"
serde = "1.0"
