[package]
edition = "2021"
name = "methods-guest"
version = "0.1.0"

[workspace]

[build-dependencies]
risc0-build = "0.11"

[dependencies]
risc0-zkp = { version = "0.11", default-features = false }
risc0-zkvm-guest = "0.11"
serde = "1.0"
